version: "3.8"

services:
    app:
        image: robert-jan/dive:dev
        working_dir: /dive
        entrypoint: dotnet test --logger:"trx;" -- xunit.parallelizeTestCollections=false
        volumes:
            - test-storage:/dive/storage
            - ./src:/dive/src
            - ./tests/.logs:/dive/tests/.logs
            - ./tests/Unit:/dive/tests/Unit
            - ./tests/Integration:/dive/tests/Integration
    db:
        volumes:
            - test-database:/var/lib/postgresql/data

volumes:
    test-storage:
        driver: "local"
    test-database:
        driver: "local"