version: "3.8"

services:
    app:
        container_name: application
        image: rjvdelst/dive:latest
        environment:
            - "ConnectionStrings__PostgreSQL=Server=database; Port=5432; Database=dive; Username=dive; Password=dive;"
        ports:
            - "8080:80"
        volumes:
            - storage:/dive/storage
        networks:
            - network
        depends_on:
            - db
    db:
        container_name: database
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: dive
            POSTGRES_PASSWORD: dive
            POSTGRES_DB: dive
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - network
networks:
    network:
        driver: "bridge"

volumes:
    storage:
        driver: "local"
    database:
        driver: "local"
