version: "3.8"

services:
    app:
        image: robert-jan/dive:dev
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        ports:
            - "5000:5000"
        volumes:
            - ./src:/dive/src