name: "Tests"
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build develop image
        run: make dev-image

      - name: Run unit tests
        run: make unit

      - name: Run integration tests
        run: make integration

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
            name: logs
            path: tests/Artefacts