name: "Tests"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  tests:
    name: Run unit/integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build develop image
        run: make image/dev

      - name: Run unit tests
        run: make test/unit

      - name: Run integration tests
        run: make test/integration

      - name: Report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: xUnit Tests            
          path: tests/Artefacts/log.*.trx
          reporter: dotnet-trx
          fail-on-error: 'false'

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
            name: logs
            path: tests/Artefacts