name: "Tests"
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build develop image
        run: make dev-image

      - name: Run test suite
        run: make tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
            name: logs
            path: tests/.logs